# Generated by Django 5.0.6 on 2024-06-01 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restfulapp2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=100)),
                ("course_code", models.CharField(max_length=8)),
                ("certificate", models.BooleanField()),
                ("course_duration", models.TimeField()),
                ("course_domain", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="favorite_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="restfulapp2.courses",
            ),
        ),
    ]
