# Generated by Django 5.0.6 on 2024-06-01 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restfulapp2", "0002_courses_person_favorite_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="favorite_color",
        ),
        migrations.DeleteModel(
            name="Courses",
        ),
    ]
